version: '3.8'

services:
  app:
    image: tomaryabinina/analytics-trainer:develop
    container_name: analytics-app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - trainer-network

networks:
  trainer-network:
    driver: bridge
